config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :weights

  devise_for :users

  authenticated :user do
    root "weights#index", as: "authenticated_root"
  end

  root 'welcome#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :weights
end

app/models/weight.rb
class Weight < ActiveRecord::Base

  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :find_weight, only: [:show, :edit, :update, :destroy]

  def index
    @weights = Weight.all.order("created_at DESC")
  end

  def show
  end

  def new
    @weight = current_user.weights.build
  end

  def create
    @weight = current_user.weights.build(weight_params)

    if @weight.save
      redirect_to @weight
    else
      render 'new'
    end
  end

  private

  def weight_params
    params.require(:weight).permit(:reading)
  end

  def find_weight
    @weight = Weight.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Weight Grapher
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav.navbar.navbar-default
      .container
        .navbar-brand
          = link_to root_path do
            span Weight
            span Grapher
          end

        - if user_signed_in?
          ul.nav.navbar-nav.navbar-right
            li= link_to "Log Out", destroy_user_session_path, method: :delete
        - else
          ul.nav.navbar-nav.navbar-right
            li= link_to "Sign Up", new_user_registration_path
            li= link_to "Log In", new_user_session_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

    = yield

app/views/weights/_form.html.slim
= simple_form_for @weight do |f|
  = f.input :reading
  = f.button :submit, class: "btn btn-default"

app/views/weights/index.html.slim
/- @weights.each do |weight|
  / h2= link_to weight.reading, weight
  / p= weight.created_at.strftime("%A %d %b %Y")
  / p= weight.reading
.container.weight-wrapper
  - if user_signed_in?
    = link_to "Add New Weight", new_weight_path, class: "btn btn-default"
    // div#weightgraph
    = content_tag :div, "", class: "weightgraph", id: "weightgraph", data: {weights: @weights}

app/views/weights/new.html.slim
h2 Add New Weight

= render 'form'

app/views/weights/show.html.slim
p= @weight.reading
p= @weight.created_at.strftime("%A %d %b %Y")

= link_to "All Weights", weights_path, class: "btn btn-default"
= link_to "Edit", edit_weight_path(@weight), class: "btn btn-default"
= link_to "Delete", weight_path(@weight), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"

app/views/welcome/index.html.slim
.welcome-wrapper
  .container
    .col-md-6.col-md-offset-3
      h2 Welcome to WeightGrapher
      h4 The app that puts your weight on a graph, and nothing else.
      